name: deploy-supabase
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Push DB migrations to remote
        env:
          DB_URL: postgresql://postgres:${{ secrets.SUPABASE_DB_PASSWORD }}@db.${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co:5432/postgres
        run: |
          supabase db push --db-url "$DB_URL"

      - name: Set Edge Function secrets
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          set -euo pipefail
          SUPABASE_URL="https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co"
          supabase secrets set \
            SUPABASE_URL="$SUPABASE_URL" \
            SUPABASE_SERVICE_ROLE_KEY="${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

      - name: Deploy all Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          set -euo pipefail
          if [ -d supabase/edge ]; then
            for d in supabase/edge/*; do
              [ -d "$d" ] || continue
              name=$(basename "$d")
              echo "Deploying function: $name"
              supabase functions deploy "$name" --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
            done
          else
            echo "No supabase/edge directory found; skipping function deploys."
          fi
